["提供本意图槽位数据", "Saya ingin order mobil langsung, Comprehensive ya", "ID"],
["提供本意图槽位数据", "Upload STNK mobil saya, lalu KTP", "ID"],
["提供本意图槽位数据", "Mau langsung order motor, TLO coverage", "ID"],
["携带描述提供本意图槽位数据", "Mobil baru saya tahun 2022, mau langsung order, BSTK sudah siap", "ID"],
["携带描述提供本意图槽位数据", "Saya ingin langsung order mobil Honda 2021, Comprehensive", "ID"],
["提供本意图槽位数据", "Mobil lama saya STNK dan KTP sudah siap, ingin langsung order", "ID"],
["携带描述提供本意图槽位数据", "Saya mau order mobil baru Toyota 2020, Comprehensive, BSTK siap", "ID"],
["提供本意图槽位数据", "Mau order motor Yamaha baru, TLO", "ID"],
["提供本意图槽位数据", "Mobil baru saya, mau langsung order, upload BSTK dan KTP", "ID"],
["携带描述提供本意图槽位数据", "Saya mau order mobil lama saya, foto STNK, KTP, dashboard depan-belakang-samping sudah siap", "ID"],
["提供本意图槽位数据", "Car, please order directly with Comprehensive", "EN"],
["提供本意图槽位数据", "I want to submit my new car order, here are my BSTK and KTP", "EN"],
["携带描述提供本意图槽位数据", "Car from 2020, I have uploaded STNK and KTP, order directly please", "EN"],
["提供本意图槽位数据 + 意图切换", "I want to order a car directly, and also ask about payment status", "EN"],
["携带描述提供本意图槽位数据", "Motorbike 2021, uploaded KTP and STNK, want to order directly", "EN"],
["提供本意图槽位数据", "I want to order my car directly, coverage Comprehensive", "EN"],
["携带描述提供本意图槽位数据", "My new car 2022, BSTK ready, please place the order directly", "EN"],
["提供本意图槽位数据 + 意图切换", "I want to order directly, but also want to check claim conditions", "EN"],
["提供本意图槽位数据", "Order new motor, TLO coverage, KTP uploaded", "EN"],
["携带描述提供本意图槽位数据", "I want to order car directly, upload dashboard photos and KTP done", "EN"],
["提供本意图槽位数据", "我要直接下单买车，全险", "CN"],
["携带描述提供本意图槽位数据", "我要直接下单新车，全损险，BSTK已准备好", "CN"],
["提供本意图槽位数据 + 意图切换", "我要直接下单，但想先看一下保险产品对比", "CN"],
["携带描述提供本意图槽位数据", "我的旧车 STNK、KTP、前后左右车照都已准备好，想直接下单", "CN"],
["提供非本意图的槽位数据", "Saya mau cek premi mobil saya", "ID"],
["提供非本意图的槽位数据", "How much commission I get for this product?", "EN"],
["提供非本意图的槽位数据", "我想知道保险条款中的免责条款", "CN"],
["携带描述提供非本意图槽位数据", "Saya ingin tahu syarat & ketentuan polis, tapi saya juga mau order mobil baru", "ID"],
["提供非本意图的槽位数据 + 意图切换", "I want to check quote, then order car directly", "EN"],
["携带描述提供非本意图槽位数据 + 意图切换", "我要先查询理赔流程，然后再直接下单", "CN"],
["提供不常见的槽位数据", "Saya mau order mobil baru dengan coverage TLO tapi tanpa upload KTP dulu", "ID"],
["提供不常见的槽位数据", "Order motor tapi tanpa memilih tipe coverage dulu", "ID"],
["携带描述提供不常见的槽位数据 + 意图切换", "I want to order my car, but first need to ask about Fuse service", "EN"],
["提供不常见的槽位数据", "我要下单新车，但不打算提供保险公司信息", "CN"],
["指令-skip", "skip", "EN"],
["指令-place another order", "Buat transaksi baru", "ID"],
["指令-place another order", "Start a new order", "EN"],
["指令-skip", "跳过", "CN"],
["咨询Fina->不携带槽位数据", "What is FUSE?", "EN"],
["咨询Fina->携带槽位数据", "Saya ingin info tentang Fuse Pro dan cara menggunakannya untuk mobil saya", "ID"],
["咨询Fina->携带槽位数据", "我想了解Fina的服务能否直接用于我的新车下单", "CN"],
["Complaint Fina", "为什么你没有回复我？", "CN"],
["质疑Fina输出", "Your order link is expired", "EN"],
["Complaint Fina", "Kenapa lama sekali responsnya?", "ID"],
["小置信差触发（smallMargin）", "Saya mau order mobil baru, Comprehensive atau TLO ya?", "ID"],
["意图冲突触发（mutualExclusive）", "I want to order a car and make a claim at the same time", "EN"],
["低置信度越域触发（oodLowConf）", "Apakah Fina bisa menjual tiket konser?", "ID"],
["多个Tx置信度相近（tieInTx）", "I want to order a car but also check quote", "EN"]